services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-app
    container_name: portfolio-container
    restart: always
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
